### ISSUE TITLE
Simple app to display a oxcAARS example 

### ISSUE THREAD

**Issue by f-lukas** [Pandora-IsoMemo/oxcAARS#1]
Subticket for https://github.com/Pandora-IsoMemo/drat/issues/40

**Comment by arunge** [comment]
See comment: https://github.com/Pandora-IsoMemo/deBInferS/issues/1#issuecomment-2326798149

**Comment by f-lukas** [comment]
The app is deployed but there is an error during startup. It might be necessary to install Oxcal instead of calling `quickSetupOxcal()`. We can look at it later as this app is currently on hold.

**Comment by f-lukas** [comment]
> The app is deployed but there is an error during startup. It might be necessary to install Oxcal instead of calling quickSetupOxcal(). 

The error was not related to this. A [main](https://pandoraapp.earth/app/oxcaars) and [beta](https://pandoraapp.earth/app/oxcaars-beta) version containing a minimal example is now deployed.
